### ISSUE TITLE
[BUG] [your title here]

### ISSUE THREAD

**Issue by call4piyush** [iamkroot/ilc-scraper#24]
**Context**
* OS: Windows 10 x64 1909
* Install method: Executable
* Your location: Outside campus
* Course URL:  https://a.impartus.com/ilc/#/course/160200/706
* Lecture range: ALL

**Additional context**

**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/9108139/80285266-45afe200-8741-11ea-9960-157020167058.png)

**Program output**
<details>
<summary>Click to see output</summary>
<p>

```
*PASTE PROGRAM OUTPUT HERE* (Remove this line)

Traceback (most recent call last):
  File "ilc_scrape.py", line 345, in <module>
  File "ilc_scrape.py", line 335, in main
  File "multiprocessing\pool.py", line 276, in starmap
  File "multiprocessing\pool.py", line 657, in get
  File "multiprocessing\pool.py", line 121, in worker
  File "multiprocessing\pool.py", line 47, in starmapstar
  File "downloader.py", line 166, in download_stream
  File "downloader.py", line 104, in get_angle_playlists
TypeError: list indices must be integers or slices, not NoneType
Processing 01. Platform Link Check 2020-03-24.mkv
Processing 03. platform connectivity check 2020-03-26.mkv
Processing 05. Python Fundamentals For Data Science 1 2020-04-04.mkv
Processing 07. Python 3 2020-04-11.mkv
Processing 09. Session 5 2020-04-18.mkv
<class 'TypeError'> list indices must be integers or slices, not NoneType <traceback object at 0x000002BCC274E5C8>

</p>
</details>

**Comment by iamkroot** [comment]
STOP CREATING DUPLICATE ISSUES.
