### ISSUE TITLE
Facing issue with ffmpeg extrating video

### ISSUE THREAD

**Issue by ksanthosh82** [iamkroot/ilc-scraper#27]
Hi, 
When I installed all dependencies and tried extracting the videos, I am facing below errors

**_<class 'TypeError'> 'NoneType' object is not subscriptable <traceback objec>...._**

Kind of tried skipping such none types but getting below error 

**_Downloading using ffmpeg
ffmpeg error: [hls @ 0x3876a80] Error when loading first segment_** 

Can you please assist here?

**Comment by iamkroot** [comment]
Please fill the *entire* bug report, providing all the details. This error was faced by many others, look through the closed issues.

**Comment by ksanthosh82** [comment]
Hi,
Adding screenshots for more detils.

![image](https://user-images.githubusercontent.com/8243661/84563421-16991280-ad79-11ea-8e8c-d2ea850950c4.png)

The log error is thi. 

<class 'TypeError'> 'NoneType' object is not subscriptable <traceback object at 0x7f67d5f2ce80>
Traceback (most recent call last):
  File "ilc_scrape.py", line 349, in <module>
    main()
  File "ilc_scrape.py", line 339, in main
    pool.starmap(download_stream, task_args)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/nikitha/py_dev/ilc-scraper/downloader.py", line 181, in download_stream
    add_inputs(token, cmd, angle_playlists, angle)
  File "/usr/nikitha/py_dev/ilc-scraper/downloader.py", line 149, in add_inputs
    extract_enc_keys(angle_pls, token)
  File "/usr/nikitha/py_dev/ilc-scraper/downloader.py", line 121, in extract_enc_keys
    key_url = PAT.search(line)["key_url"]
TypeError: 'NoneType' object is not subscriptable

**Comment by iamkroot** [comment]
Sadly I don't have access to the course on impartus, so I can't debug this myself. Read through [this](https://github.com/iamkroot/ilc-scraper/issues/19#issuecomment-619543265) comment (and the entire issue too) and send the stored file here.
